# Generated by Django 2.2.4 on 2020-07-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='uno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
